### ISSUE TITLE
Error when you try to upload a new FIle

### ISSUE THREAD

**Issue by pegus** [saltcorn/saltcorn#1030] opened 2021-12-30 16:44 UTC
When I tried to add new files, I got this message:

error: duplicate key value violates unique constraint "_sc_files_pkey"
    at Parser.parseErrorMessage (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by glutamate** [comment] 2022-01-05 10:55
The cause of this bug is explained in this SO answer https://stackoverflow.com/questions/4448340/postgresql-duplicate-key-violates-unique-constraint and hopefully fixed in #1035 which should prevent this from happening in new instances after a restore

To fix this in an existing instance where you are seeing this problem, deleting any existing file should trigger the necessary re-indexing @pegus (after #1035 )

**Closed** 2022-03-09 19:40 UTC
