### ISSUE TITLE
SQLView: empty SQL result returns error in HTML output

### ISSUE THREAD

**Issue by 0luckyluke** [saltcorn/saltcorn#2233] opened 2024-01-23 14:22 UTC
**Describe the bug**
An empty SQL result (no rows selected) returns error in HTML output

**To Reproduce**

**Expected behavior**
empty HTML 

**Screenshots**
![afbeelding](https://github.com/saltcorn/saltcorn/assets/156822398/9a00b100-8a62-4f76-8d2c-8d5a7bf6108c)

TypeError: Cannot read properties of undefined (reading 'f_busy')
    at eval (eval at template (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/underscore/underscore-node-f-pre.js:917:14), <anonymous>:6:16)
    at template (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/underscore/underscore-node-f-pre.js:924:19)
    at Object.run (/home/saltcorn/plugin_packages/@saltcorn/sql/index.js:120:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at View.run (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:457:14)
    at View.run_possibly_on_page (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:552:18)
    at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/view.js:73:23
**Additional context**

**Comment by 0luckyluke** [comment] 2024-01-23 14:24
When the result set is not empty, everything works fine.

**Comment by glutamate** [comment] 2024-01-31 15:25
duplicate of https://github.com/saltcorn/sql/issues/2

**Closed by glutamate** 2024-01-31 15:25 UTC
Labels: bug
