### ISSUE TITLE
Update multiple list at once

### ISSUE THREAD

**Issue by itachiemashita89** [saltcorn/saltcorn#1799] opened 2023-05-02 04:04 UTC
Hello,
I do have list record that by right manager level view the list and need give "approval" by click on selected record as show in below image.
My question is, any way the manager to select all the row and just click once (in this case select "Approve") and all selected row fill with the fill select instead of click one by one row.
 
![Screenshot 2023-05-02 113004](https://user-images.githubusercontent.com/91925990/235576242-a7af78f6-e14a-4d98-853c-987a338c3f3c.png)

I do use Tabulator that able do "select all" but not found yet any function to what I describe above.
Suppose record to approve is list of record (by monthly) submition from staff. For now I only able do by listing one by one approval.
Thanks in advance if can share me some idea or method.
Thanks.

**Comment by glutamate** [comment] 2024-11-06 21:54
(dupe of https://github.com/saltcorn/saltcorn/issues/641) :

this is now implemented in tabulator module 0.10.0. in the "Selected rows action" setting (functionality tab) you can now choose an edit view of the same table. When clicked the edit form comes up in a popup. If save the fields that are filled out in the form will be applied to all the selected rows. Note that the Edit view needs to have a simple Save action button for this to work

**Closed by glutamate** 2024-11-06 21:54 UTC
Labels: question
