### ISSUE TITLE
Table write access rights can be bypassed

### ISSUE THREAD

**Issue by mhier** [saltcorn/saltcorn#1522] opened 2022-12-12 20:24 UTC
**Describe the bug**
When configuring a table to require e.g. the admin role to write, writing to the table is still possible to non-admin users, if an edit view exists which has a lower access role requirement and the user knows/guesses the link to that view. This is particularly problematic when using "owned" tables and allowing non-admin users to edit their own rows. In such case an edit view accessible by non-admin users has to exist. The user merely needs to replace the id passed with the URL to edit any arbitrary row of the table.

**To Reproduce**
1. Create table with user/admin read/write access rights, add e.g. a string column
2. Create edit view for that table with user access rights
3. Create a row in that table with some arbitrary data
4. Log in with different account which only has the user role
5. Type in the URL of the edit view, append "id=1" (replace "1" with the row id if necessary)
6. Enter any data and save
7. Log in again as admin, open the table content and verify that the data has been modified

**Expected behavior**
Some access denied error message should appear when the user attempts to save data (server-side checking to prevent loop holes).

**Comment by anzacloud** [comment] 2022-12-14 12:38
Can this be addressed by setting the option of running the view (You set this on the first step of creating an edit view) to admin only?

**Comment by mhier** [comment] 2022-12-14 13:08
> Can this be addressed by setting the option of running the view (You set this on the first step of creating an edit view) to admin only?

In most cases, yes. If you want users to edit their own data, this does not work since the edit view cannot be executed by them at all then. That is the situation in which I noticed this bug.

**Comment by anzacloud** [comment] 2022-12-14 13:11
The way I have made it work for me is setting the edit view to only run for admin, edit only if owner, and then having the view as a pop up in the page that I want the edit (by owner) to happen. That seems to work well.

**Comment by mhier** [comment] 2022-12-14 13:26
Honestly, I would expect any view configured to run only for admins would not run for non-admins in any condition. This sounds more like another bug than a feature...
It looks to me that the right management system of Saltcorn still has many loop holes.

**Comment by anzacloud** [comment] 2022-12-14 13:28
> The way I have made it work for me is setting the edit view to only run for admin, edit only if owner, and then having the view as a pop up in the page that I want the edit (by owner) to happen. That seems to work well.

I can confirm this prevents creating new records.

> Honestly, I would expect any view configured to run only for admins would not run for non-admins in any condition. This sounds more like another bug than a feature... It looks to me that the right management system of Saltcorn still has many loop holes.

That is indeed true. There seems to be a bug. Sorry I hadn't tested whether the record had been created as there are no alerts for failed creation on Saltcorn.

**Comment by glutamate** [comment] 2022-12-14 13:51
Hi @mhier @anzacloud I am aware of this and this will change in a release in the near future so we enforce the full permission lattice. Currently, it is the view permission that determines whether you have access. In the beginning I did it this way because it allowed you to do some tailoring of allowing you to edit some rows but not others. But this is no longer necessary now that we have ownership formulae.

In the future it will be the lower bound of the view and table permissions. This is why I added a warning at the top of the view list to notify if there are any views that are lower than the access settings in the table.

**Comment by mhier** [comment] 2023-01-18 20:17
I now discovered kind of the opposite problem: I have a table with ownership. The read and write permissions are configured to staff, so normal users cannot read or write anything except the entries they own. Normal users have a list view showing all entries owned by them. The list view has action buttons to toggle some boolean columns in the table. When hitting the button, users now get a write permission error message ("Not allowed to write to table [...]"). This was different in previous versions of Saltcorn.

Shall I create a separate issue for this new problem, or is it part of this issue?

**Comment by glutamate** [comment] 2023-01-25 12:13
This is fixed in #1594

**Closed** 2024-10-10 09:08 UTC
Labels: bug
