### ISSUE TITLE
html-pdf-node or other plugins in mind for PDF generation?

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#821] opened 2021-08-20 04:48 UTC
will it be included in the roadmap (or be added) in the future?

**Comment by glutamate** [comment] 2021-08-21 08:20
duplicate of #430 - but thanks for suggesting that library

**Closed by glutamate** 2021-08-21 08:20 UTC

**Comment by hardc0l2e** [comment] 2021-08-21 11:45
> duplicate of #430 - but thanks for suggesting that library

Thanks, got it.
