### ISSUE TITLE
Unable to restart Saltcorn after upgrade

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#2595] opened 2024-08-15 05:29 UTC
After upgrading from 0.9.6 b20 in the web UI, the Saltcorn service did not restart. Looking in syslog, I see ten restart attempts, each of which fails with the error message " ReferenceError: ReadableStream is not defined". Attempting to start Saltcorn manually from the prompt throws the same error, but no other messages or clues.

Steps to reproduce the behaviour:
1. Go to the system page.
2. Check current version is 0.9.6 b20
3. Click check for upgrades
4. Click to upgrade
5. Wait for the upgrade to finish and click the "back" button in the browser, as prompted.
6. Refresh the page as prompted.

Expected behaviour: The page is refreshed and we see the Saltcorn system page.

Problem behaviour: A "service unavailable" message is thrown, as the service behind it is not running.

I'm going to see if I can figure out how to revert to Beta 20 for now.

**Comment by glutamate** [comment] 2024-08-15 07:27
to downgrade, run this as the saltcorn user:

`npm install -g @saltcorn/cli@0.9.6-beta.20 --unsafe`

Which version of node is installed (run `node --version`) 

And can you also paste more of the error message from the log @glimmung

**Comment by glimmung** [comment] 2024-08-15 08:03
The downgrade worked perfectly, and I'm now back up and running - thank you for the quick response.

Node is v16.20.2

At the prompt, attempting to restart Saltcorn just threw "ReferenceError: ReadableStream is not defined" with no other errors. In syslog it was the same - that single error, but bracketed in messages re. service restart and 10x retries. Is there another log that would be helpful?

**Comment by glutamate** [comment] 2024-08-15 08:40
no if there is no more in the log thats ok. I'll look and see if it is a general problem with node 16. How did you install @glimmung  - DigitalOcean one-click, docker, npx saltcorn-install .. ?

**Comment by glimmung** [comment] 2024-08-15 08:53
This instance is manually installed on an Ubuntu 20.04 server, using the then-current instructions, but adapting them for Apache rather than Nginx.

**Comment by glutamate** [comment] 2024-08-15 09:33
I can reproduce on ubuntu 20.04 running node 16. It works with node 18 so i recommend upgrading to that

**Comment by glimmung** [comment] 2024-08-15 09:35
Great, thank you - I'll upgrade Node and them Saltcorn, and will update here when done.

**Comment by glimmung** [comment] 2024-08-15 10:10
All done - now on Node v18.20.4, Saltcorn upgraded to v0.9.6 (no longer beta), and all seems to be well so far.

**Comment by glutamate** [comment] 2024-08-15 10:52
ok. For anyone else, 0.9.7 is working again with node 16

**Comment by unquietwiki** [comment] 2024-08-15 14:12
This might be related. Have a 0.9.6 b20 instance that wanted to upgrade to 0.9.6; did that, and it was still on b20 after refresh. Then tried to choose version, and saw 0.9.7; tried that, and still on b20. Running on Node v20.16.0 with latest stable Debian.

**Comment by Ingenu1ty** [comment] 2024-08-15 15:17
> This might be related. Have a 0.9.6 b20 instance that wanted to upgrade to 0.9.6; did that, and it was still on b20 after refresh. Then tried to choose version, and saw 0.9.7; tried that, and still on b20. Running on Node v20.16.0 with latest stable Debian.

Same problem. Node 20, Ubuntu 24

**Comment by 0luckyluke** [comment] 2024-08-20 13:31
> This might be related. Have a 0.9.6 b20 instance that wanted to upgrade to 0.9.6; did that, and it was still on b20 after refresh. Then tried to choose version, and saw 0.9.7; tried that, and still on b20. Running on Node v20.16.0 with latest stable Debian.

Same problem here; upgrade to 0.9.7 and still 0.9.6b20 after restart. Node 20 on Ubuntu 24

**Comment by derhames** [comment] 2024-08-21 09:21
Same here. I tried the upgrade through the system page, manually via terminal and I also tried to install a specific version (0.9.7) but I always get the same result: the version number still shows 0.9.6.b20. after a refresh or even a restart of the service.

I just noticed this message about Docker in the output after the upgrade:
```changed 1795 packages in 20s

158 packages are looking for funding
  run `npm fund` for details
Pulling the cordova-builder docker image...
Error: spawn docker ENOENT
Pull done with code ENOENT
Upgrade done (if it was available) with code 0.
```
There is no docker on this system, so wondering if that might be related.

Node 18 on Debian 12. Saltcorn was installed using the automated script: npx saltcorn-install

**Comment by christianhugoch** [comment] 2024-08-21 12:16
Hi, the docker message shouldn't be a problem. This is just an optional step.

**Comment by christianhugoch** [comment] 2024-08-21 12:35
Can you check the version with
npm list -g

and compare it with the gui value?

**Comment by derhames** [comment] 2024-08-21 13:00
here it displays correctly version 0.9.7
```
@***@***.***
```

**Comment by christianhugoch** [comment] 2024-08-21 15:22
Because of a dependency problem, related to node 16 we had to disable a part of the release mechanism. This will be fixed soon.

**Comment by Ingenu1ty** [comment] 2024-08-21 15:38
> Because of a dependency problem, related to node 16 we had to disable a part of the release mechanism.

maybe just drop support for node 16? I think people use node 16 just because they copy paste from the SC install documentation :-)

**Comment by christianhugoch** [comment] 2024-08-25 17:13
Yes, but we can still save it easily. There was an update of cheerio with a dependency that does not run on node 16. So, I believe we just have to set a static package version in chaos-guinea-pig.

From @saltcorn-cli, we still support node 14, perhaps we should think about dropping that.

**Comment by christianhugoch** [comment] 2024-08-29 13:49
I think it shoudl work again with 0.9.8-rc.0

Just tried it with node 16.14.0 and 20.16.0

**Comment by unquietwiki** [comment] 2024-08-29 16:23
Yeah, can verify that upgrading to 0.9.8-rc.0 gets rid of the persistent upgrade message. Thanks!

**Closed** 2024-09-21 08:51 UTC
Labels: bug
